### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by monerobull** [hundehausen/xmr-node-explorer-nextjs#8]
I git cloned the repository, entered it but getting
` monoero-node-explorer-db | PostgreSQL Database directory appears to contain a database; Skipping initialization
monoero-node-explorer-db |
monoero-node-explorer-db | 2022-11-18 10:37:41.044 GMT [1] FATAL:  unrecognized configuration parameter "stats_temp_directory"
monoero-node-explorer-db exited with code 1` when starting. I can get to the database admin page and log in but have no idea what i am supposed to do.

**Comment by monerobull** [comment]
@hundehausen thanks for the quick reply!
im now getting:

```
monoero-node-explorer-db | 2022-11-18 14:16:48.745 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
monoero-node-explorer-db | 2022-11-18 14:16:48.745 UTC [1] LOG:  listening on IPv6 address "::", port 5432
monoero-node-explorer-db | 2022-11-18 14:16:48.750 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
monoero-node-explorer-db | 2022-11-18 14:16:48.758 UTC [28] LOG:  database system was shut down at 2022-11-18 14:16:41 UTC
monoero-node-explorer-db | 2022-11-18 14:16:48.765 UTC [1] LOG:  database system is ready to accept connections
```
Im using https://github.com/lalanza808/docker-monero-node on yunohost which i believe already uses postgress on port 5432(?) so I've changed the external port to 5431 and my .env now looks like this:
`DATABASE_URL = 'postgresql://node:node@127.0.0.1:5431/node'` (is that right or do i need to put something else there?)
Port 3000 is also already in use by the nodes grafana instance.

i also have no idea what yarn or npx does 😅

**Comment by hundehausen** [comment]
Hey @monerobull,

you did everything right. You changed the port of your second postgres db.
So the new problem is, that on port 3000 there is already an instance of grafana running.
What you can do is to edit the dev script the package.json file:
"dev": "next dev --port 3001",

Now, xmr-node-explorer-nextjs is running on port 3001.

**Comment by hundehausen** [comment]
yarn is a packet manager very similar to npm.
npx is a package or binary runner. You can use it to execute cli tools, and you don't have to download and install them.

**Comment by monerobull** [comment]
This is what I get when changing the provider in schema from mysql to postgresql and commenting out the previewFeatures:
```
Environment variables loaded from ../.env
Prisma schema loaded from schema.prisma
Error: Schema validation error - Error (get-config wasm)
Error code: P1012
error: Error validating datasource `db`:
This option can only be set if the preview feature is enabled in a generator block.

Example:

generator client {
    provider = "prisma-client-js"
    previewFeatures = ["referentialIntegrity"]
}

  -->  schema.prisma:5
   |
 4 |   url                  = env("DATABASE_URL")
 5 |   referentialIntegrity = "prisma"
 6 | }
   |

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 4.6.1
```
When I dont comment them out, it looks better (?) but still fails:
```
Environment variables loaded from ../.env
Prisma schema loaded from schema.prisma
Datasource "db": PostgreSQL database "node", schema "public" at "127.0.0.1:5431"

Already in sync, no schema change or pending migration was found.

Running generate... (Use --skip-generate to skip the generators)
Usage: yarn [options]

yarn: error: no such option: -D
Error: Command failed with exit code 2: yarn add -D prisma@4.6.1
```
Also, doing "yarn install" just returns "No such file or directory: 'install'"

I could launch prisma studio and access it but node only showed an error

**Comment by hundehausen** [comment]
comment out referentialIntegrity = "prisma" if you are using postgresql

**Comment by hundehausen** [comment]
Have you installed yarn on your machine?

**Comment by monerobull** [comment]
Btw i can now select node in prisma studio but the list is empty. i think the only problem left is that i cant connect to 3001 even though i added the --port 3001 thing in package.json 
I get "Connection was reset" in the browser and `channel 3: open failed: connect failed: Connection refused` in the terminal

**Comment by hundehausen** [comment]
Mhh I don't know. Maybe try another port then.

**Comment by monerobull** [comment]
So all the changes I do to a fresh install:

- change port number in .env (in the database link)
- change to postgresql in prisma schema, comment out prisma right beneath that and comment out previewFeatures
- ad a different port in package.json

did i forget anything?

**Comment by hundehausen** [comment]
Change back package.json to original and start project with `yarn dev -p 3001`

**Comment by monerobull** [comment]
... i installed npm and did it with that and everything worked 😅
something was wrong with yarn, not sure, and i wasnt aware that the purpose of it was to install dependencies so i didnt really investigate.
guess i learned something new today.

i thought it would somehow add the nodes my monero node sees to the list like monero.fail, does it not do that?
also, what does it do to get countries? i have seths node with ip 172.86.183.74 marked as USA while its marked Germany on your instance.

**Comment by monerobull** [comment]
now, how can i do `npm run dev` but have it run detached/in the background?

**Comment by hundehausen** [comment]
It's already possible to find connected peers to your own node, when you are connecting to it unrestricted, I think. It might work for unrestricted rpc connections. While it's not possible over the ui it is possible over an API call. You can do this with postman. But I found a bug, let me fix that tonight and then I'll help you.

**Comment by hundehausen** [comment]
Hey @monerobull,

if you pull the repo with git pull, you can find some improvements. With the endpoint GET /api/findPeers you can manually find peers for a node in your database that respond to the get_info rpc call to your database as well. All you need is the id of your node. Give the id via GET params in HTTP request. You can additionally add the parameter addToDb = 'true' so the application will add all nodes as well.

For letting the application run, I can think of adding it to the docker-compose file. Stay tuned for that.

For the location, I use the service from https://ipapi.co. I have no idea why there are different results.

**Comment by monerobull** [comment]
Awesome, looking forward to all the improvements. Thanks for taking the time to do all of this!
